Open-Orange-Button/Orange-Button-Taxonomy

Master-OB-OpenAPI.json

Small change to a sample value to demonstrate git capabilities

Added Sample Value for PVSystem.CapacityAC

---

Master-OB-OpenAPI.json

Changed Projects -> Jobs,  Project - > Job,  ProjectPriceAmt -> JobPriceAmt

Project -> Job Naming convention changes

---

Master-OB-OpenAPI.json

Removing quotation from numerical values within the taxonomy.

Changing Numerical values to remove "" 

---

Master-OB-OpenAPI.json

Additional numerical sample value changes under Orientation object.

Orientation numerical sample value changes 

---

Master-OB-OpenAPI.json

Added new definition for `ProdEnergyStorage`

ProdEnergyStorage Initial Definition

---

Master-OB-OpenAPI.json

Closes #34 
Changed Taxonomy element string to Bool or Number based on object value.

Changed taxonomy data type to match object value

---

Master-OB-OpenAPI.json

Remove solar-types:uuidStdItemType

---

docs/whatsnew/2202.1.0.rst

Create whatsnew document structure

---

Master-OB-OpenAPI.json
docs/whatsnew/2202.1.0.rst

Created Portfolio and Project objects initiated hierarchy.

Added Portfolio, projects/project, sites

---

Master-OB-OpenAPI.json
docs/whatsnew/2202.1.0.rst

Added many objects to ProdOptimizer

---

Master-OB-OpenAPI.json
docs/whatsnew/2202.1.0.rst

A comment
Added Cec Certs to ProdBattery

Added CEC Certs to ProdBattery cert enum

---

Master-OB-OpenAPI.json
docs/whatsnew/2202.1.0.rst

Adding sample values to LegalEntityIdentifier and TaxID.
Changing sample values of HomePhone, WorkPhone, and MobilePhone.

Adding InstallerName to Installer, Adding Sample Values for Installer Sample JSON

---

Master-OB-OpenAPI.json
docs/whatsnew/2202.1.0.rst

Add elements: 
* ForecastID
* ForecastName
* ForecastScopeID
* ForecastScopeType
* ForecastIssueTime
* EnergyACArray
* PowerACArray
* TempAmbArray
* TempModuleArray
* IrradGlobHorizArray
* IrradPlaneOfArrayArray
Add objects:
* Forecast
* ForecastScope
Add units:
* ForecastScopeTypeItemType

Add Forecast data model

---

docs/whatsnew/2207.0.0.rst
docs/whatsnew/2207.1.0.rst

Copies content from incorrectly named 2202.1.0.rst to 2207.0.0.rst.
Adds text for #82 to 2207.1.0.rst.

Whatsnew fix

---

Master-OB-OpenAPI.json
docs/whatsnew/2207.1.0.rst

Adds AHJLevelCode and elements for special cases.

---

Master-OB-OpenAPI.json
docs/whatsnew/2207.1.0.rst

Creates elements: EnergyACAnnualP50, EnergyACAnnualP90.
Creates objects: EnergyModelInput, EnergyModelOutput, EnergyModelScope
Deletes element: EnergyModels (was an array of EnergyModel)
Adds revised EnergyModel to PVSystem.

Overhaul EnergyModel

---

Master-OB-OpenAPI.json
docs/whatsnew/2207.1.0.rst

add CECListingDate to ProdModule, ProdInverter

---

Master-OB-OpenAPI.json
docs/whatsnew/2207.1.0.rst

make ForecastScope again, remove ForecastScopeID

---

Master-OB-OpenAPI.json
docs/whatsnew/2209.1.0.rst

Requested changes for PV/BatterySystems, adds SystemID's array which is included in Job object. Adds Scope to Job object.

Moves System objects up level in Site.

---

Master-OB-OpenAPI.json
docs/whatsnew/2209.1.0.rst

Adds AnswerRange elements to Question.

---

Master-OB-OpenAPI.json
docs/whatsnew/2209.1.0.rst

Adds Owner, Insurer per issue 96

---

Master-OB-OpenAPI.json

I have reviewed the elements contained by the Site object and added sample values where necessary.

Updates elements of Site object to add sample values where needed.

---

Master-OB-OpenAPI.json
docs/whatsnew/2209.1.0.rst

Closes #177 
Adds DateTimeItemType and adjusts some example values.

Adds DateTimeItemType

---

Master-OB-OpenAPI.json
docs/whatsnew/2209.1.0.rst

Adds StandardTypeItemType and adds updated Enums

---

Master-OB-OpenAPI.json
docs/whatsnew/2209.1.0.rst

Adds Elements:
- AvailCapacity, AvailOperational, AvailTechnical, AvailabilityStandard, CapacityFractionAC, UpTimeTotal, DownTimeTotal
Deletes Element:
- Avail
Adds Objects:
- Availability, Availabilities, UpTime, DownTime, AvailabilityReport

Add Availability elements and objects

---

Master-OB-OpenAPI.json
docs/whatsnew/2209.1.0.rst

Adds ModuleArea to ProdModule

---

Master-OB-OpenAPI.json

Updates Duration sample value, issue #176

---

Master-OB-OpenAPI.json
docs/whatsnew/2209.1.0.rst

Adds SubstituteProducts object array.

---

Master-OB-OpenAPI.json
docs/whatsnew/2209.1.0.rst

add Comments, FileFolderURL, remove UpTimes and DownTimes

Refine Availability

---

Master-OB-OpenAPI.json
docs/whatsnew/2209.1.0.rst

merge ItemTypes listing cell technologies

---

Master-OB-OpenAPI.json

Adds Elements:
- SoilingRatio, SoilingRatios
Adds SoilingRatios to OperatingReport

add SoilingRatio

---

Master-OB-OpenAPI.json
docs/whatsnew/2209.1.0.rst

Addresses issue #217 #218  adds Scope/Definition where required.

Adds changes from issues 217,218

---

Master-OB-OpenAPI.json
docs/whatsnew/2209.1.0.rst

Closes #204 
* Creates Object EnergyProduction, EnergyImport, EnergyExport, EnergySelfConsumption
* Deletes EnergyUsage
* Edits definition for EnergyConsumption

Make trio: EnergyUsage, EnergyConsumption, EnergyProduction

---

Master-OB-OpenAPI.json
docs/whatsnew/2209.1.0.rst

Draft of elements to represents status of Site and Job. Closes #202, #200 .

Creates JobStatus element.

---

Master-OB-OpenAPI.json
docs/whatsnew/2209.1.0.rst

Adds Sample values for Availabilites and OperatingReport where they were missing. Updating PercentItemType description, adding DecimalPercentItemType and decimal_percent unit.

Avail samples

---

Master-OB-OpenAPI.json
docs/whatsnew/whatsnew_dev.rst

Removes DeviceWarranty and member elements.

---

Master-OB-OpenAPI.json
docs/whatsnew/whatsnew_dev.rst

Adds draft of Usage Tip for Scope object.

Adds usage tip to Scope object.

---

Master-OB-OpenAPI.json
docs/whatsnew/whatsnew_dev.rst

Adds IEEE 2030.5 and IEEE 2800 enums to CertificationTypeProductItemType

---

Master-OB-OpenAPI.json
docs/whatsnew/whatsnew_dev.rst

Removes CertificationTypeProduct, CertificationTypeProductItemType

---

.github/configs/schema-validator/OB-dictionaries/OB-words/OB-words.dic
Master-OB-OpenAPI.json
docs/whatsnew/whatsnew_dev.rst

Closes #254 
* New enumerations: StageItemType, StateItemType
- StateItemType overwrites OperationalStateItemType
* New elements:
- IsCancelled
- IsPaused
- Stage
* New object SystemStage (StageItemType)

implement StageItemType, StateItemType

---

Master-OB-OpenAPI-2309-0-0.json
Master-OB-OpenAPI.json
docs/whatsnew/2309.0.0.rst
docs/whatsnew/whatsnew_dev.rst

2309.0.0 release

---

Master-OB-OpenAPI.json
docs/whatsnew/whatsnew_dev.rst

* Add Failure object
* Elements for Adds FailureCause, FailureDateDetected, FailureDetectionMethod, FailureID, FailureMechanism, FailureOperatingCondition, ImpactCapability, ImpactProduction, ImpactSafety
* Adds enumerations FailureDetectionMethodItemType, FailureMechanismItemType, FailureOperatingConditionItemType, ImpactCapabilityItemType, ImpactProductionItemType, ImpactSafetyItemType

Add Failure object

---

Master-OB-OpenAPI.json
docs/whatsnew/whatsnew_dev.rst

Adds PrivateKeyAddress and updates whatsnew_dev.rst

---

Master-OB-OpenAPI.json
docs/whatsnew/whatsnew_dev.rst

Creates InsuranceType and related Enums. Cleans up EntityRole enums. Adds CerificationAgency and TestLab to EntityRole enums.

Entity type overhaul

---

.github/configs/schema-validator/OB-dictionaries/OB-words/OB-words.dic

Reduces warnings from our taxonomy checks.

New words, acronyms and abbreviations

---

Master-OB-OpenAPI.json

replace Amount by Quantity in Item objects

---

Master-OB-OpenAPI.json
docs/whatsnew/whatsnew_dev.rst

Revert cae8010

---

.github/configs/schema-validator/OB-dictionaries/OB-words/OB-words.dic
Master-OB-OpenAPI.json

Adds Groundskeeping, Document, Train, Lockout, Decommission

Add to OMActivityType enum

---

Master-OB-OpenAPI.json
docs/sphinx/source/whatsnew/whatsnew_dev.rst

Adds DPP_EU enum to IdentifierTypeItemType enum list.

DPP_EU enum addition 

---

Master-OB-OpenAPI.json
docs/sphinx/source/whatsnew/whatsnew_dev.rst

Update to Contract object

---

Master-OB-OpenAPI.json
docs/sphinx/source/whatsnew/whatsnew_dev.rst

Adds ID elements to Entity object that were previously missing IDs

Entity Cleanup

---

Master-OB-OpenAPI.json
docs/sphinx/source/whatsnew/whatsnew_dev.rst

Adds IEEE2030_5_2023 to StandardTypeItemType Enum List.  Updates whatsnew_dev.rst

Adds IEEE2030_5_2023 to StandardTypeItemType Enum List. 

---

Master-OB-OpenAPI.json
docs/sphinx/source/whatsnew/whatsnew_dev.rst

A refactor of the previous approach of time series objects.

Time series refactor

---

Master-OB-OpenAPI.json
docs/sphinx/source/whatsnew/whatsnew_dev.rst

Closes #353
Removed InveterOutput and InveterOutputs objects

Dan k learning branch

---

Master-OB-OpenAPI.json

closes #340 
Updated SigningFor description to "Entity being represented by a signature."

Updated SigningFor description

---

Master-OB-OpenAPI.json

Updated description for PVArray to include Module Group reference in the definition.
Closes #356

Updated description for PVArray to include Module Group

---

Master-OB-OpenAPI.json
docs/sphinx/source/whatsnew/whatsnew_dev.rst

Add new time series object  irradiance ts #358

---

Master-OB-OpenAPI.json
docs/sphinx/source/whatsnew/whatsnew_dev.rst

Adds snowfallTS

---

Master-OB-OpenAPI.json
docs/sphinx/source/whatsnew/whatsnew_dev.rst

Adds temperatureTs

---

Master-OB-OpenAPI.json
docs/sphinx/source/whatsnew/whatsnew_dev.rst

Adds windspeedTS

---

Master-OB-OpenAPI.json
docs/sphinx/source/whatsnew/whatsnew_dev.rst

Adds rainfallts

---

Master-OB-OpenAPI.json
docs/sphinx/source/whatsnew/whatsnew_dev.rst

Add wind direction ts #371
